### ISSUE TITLE
README improvements (27 Feb 2019)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/dashboard-js#2]
* Link to widget example in index.html should link to line number (index.html is big)
  * Should js code be separate from the index.html for clarity e.g. in app.js?
    * *we're going to have "example" section in #4*
* [x] `npm run eject` - do we need this documented (do we need rest documented or could we link to create react app docs?)
  * [x] There is a bunch of "create react app" boilerplate still in the readme.
* Explain what widgets are (a little diagram of a dashboard page)
  * *this should be part of #3 where we explain what it is*

**Comment by anuveyatsu** [comment]
FIXED.

@stefanbole can you make sure that we cover the last task from this issue in #3?
