### ISSUE TITLE
Update README to showcase its basic functionalities

### ISSUE THREAD

**Issue by stefanbole** [datopian/dashboard-js#4]
As a new User, I want to know how to use this to build my own dashboard so that I can do that …
Get started instructions or example directory … 
Add <script … dashboard-js.js></script> to your HTML file (from raw GitHub)
Add a widget placeholder <div class=”...”></div>
Configure your widgets and data sources
…
Here’s an example to get you started … 
Here’s a more complex example (e.g. London)

Acceptance criteria
---

* [x] Have an instructions section in README of how to include a dashboard-js library and how to configure widgets and data sources

* [x] Have a demo-project with the dashboard-js.js library

* [x] Have the link of the demo-project inside of README

* [x] Have a link of the city-indicators project

Tasks
---

* [x] Create a draft of the section with the instruction of how to configure the project with dashboard-js.js 

* [x] Have the draft reviewed 

* [x] Improve the draft per feedback

* [x] Push it to GitHub

* [x] Create a demo-project that uses the dashboard-js library

* [x] Have the project reviewed

* [x]   Improve the project per feedback

* [x] Push it to the GitHub

* [x] Add link in dashboard.js-js README to the demo-project

* [x] Add link in the README of the https://london.datahub.io/ as an example of a more complex project

**Comment by anuveyatsu** [comment]
@stefanbole can you please update the description of this issue with proper markdown syntax?
