### ISSUE TITLE
Install package via NPM?

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/dashboard-js#8]
Is it possible to install the package via NPM? If so, can we include the instructions in the docs? If not, can we publish the package to NPM and then add to the docs? I'm happy to help with this :)

**Comment by anuveyatsu** [comment]
@starsinmypockets hey, it isn't published on NPM but you can still install it from github. However, I'm not sure why would you need it.

**Comment by anuveyatsu** [comment]
FIXED - https://www.npmjs.com/package/@datopian/dashboard
