### ISSUE TITLE
Vega "figure" config fails for new dataset

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/dashboard-js#9]
I am trying to write a new dashboard for Montreal. I am using the london dash as a model for the project. `Figure` fails to render with the error message:

> dashboard.js:formatted:69368 Uncaught (in promise) TypeError: e.on is not a function
    at dashboard.js:formatted:69368

![image](https://user-images.githubusercontent.com/949175/59223186-4d9e7c00-8b99-11e9-9298-77ce5743c7bf.png)

Config: https://github.com/datopian/montreal-city-indicators/blob/master/widgets/publicTransit.json

Not sure what I am doing wrong here.

**Comment by anuveyatsu** [comment]
@starsinmypockets probably this is lack of documentation but by looking at your config:

* it is missing `specType` property which tells the dashboard lib what kind of widget to render. E.g., it can be `vega` or `figure`
* it is missing `spec` property:
  * spec for `figure` - https://github.com/datopian/dashboard-js/#figure-widget
  * spec for `vega` - https://datahub.io/docs/features/views#vega-graphs

**Comment by anuveyatsu** [comment]
Well, those properties are missing but the error isn't related to that.

The error is thrown here - https://github.com/datopian/dashboard-js/blob/master/src/hooks/useDatasetLoader.js#L29

I'm checking the underlying library `data.js`

**Comment by starsinmypockets** [comment]
@anuveyatsu The widget config has those properties: https://github.com/datopian/montreal-city-indicators/blob/master/widgets/publicTransit.json

**Comment by anuveyatsu** [comment]
@starsinmypockets sorry, I've missed it. 

I've just identified the source of this issue and opened https://github.com/datopian/data.js/issues/51

As a quick fix, can you re-push your dataset to datahub by removing `"pathType": "local"` field?

**Comment by starsinmypockets** [comment]
I'm not sure I understand @anuveyatsu; neither `datapackage.json` file contain `"pathType"` property.

**Comment by starsinmypockets** [comment]
Should I _add_ the `pathType` property to the `datapackage.json` file(s)?

**Comment by anuveyatsu** [comment]
@starsinmypockets are you sure that resource descriptors don't have `pathType` property? Where can I see your original `datapackage.json` file?

**Comment by starsinmypockets** [comment]
@anuveyatsu https://github.com/datopian/montreal-city-indicators/blob/master/data/kpis/datapackage.json

**Comment by rufuspollock** [comment]
@anuveyatsu this is not in the source datapackage.json but is in the datapackage.json generated on datahub.io - see https://pkgstore.datahub.io/9bfafa8c26c038399786efe07000765a/montreal-kpis/4/datapackage.json

**Comment by starsinmypockets** [comment]
True @anuveyatsu @rufuspollock -- the local datapackage.json file does _not_ contain the property, but the datahub.io copy does have it, but the working widgets have the same property, so I don't see how this is the root cause?

**Comment by anuveyatsu** [comment]
@starsinmypockets need to investigate further why the referenced data packages are working with `pathType` property.

I have published a new version of dashboard-js on NPM which should fix this issue. Could you try to use it? Thanks!

**Comment by anuveyatsu** [comment]
@starsinmypockets I guess this issue is already resolved? Do you mind to close it?

**Comment by starsinmypockets** [comment]
@anuveyatsu  Seems to load data as expected -- awesome!
![image](https://user-images.githubusercontent.com/949175/59847251-039f5e00-9330-11e9-94e1-7f2def143e71.png)

Any idea where the `undefined` is coming from, maybe I'm missing something in the config?

```json
var config = {
  widgets: [
    {
      "elementId": "testWidget",
      "view": {
        "title": "Economy",
        "legend": "Recent unemployment rate",
        "resources": [
          {
            "datasetId": "montreal-kpis",
            "name": "trips",
            "format": "json",
            "transform": [
              {
                "type": "aggregate",
                "fields": [
                  "DateDonnee"
                ],
                "operations": [
                  "argmax"
                ]
              }
            ]
          }
        ],
        "specType": "figure",
        "spec": {
          "fieldName": "Valeur"
        }
      }
    }
  ],
  datasets: ["https://datahub.io/starsinmypockets/montreal-kpis"]
}
```

**Comment by anuveyatsu** [comment]
@starsinmypockets yes, it is expecting `suffix` property like here https://github.com/datopian/city-indicators/blob/master/widgets/economy.json#L24

However, it should not render `undefined` which is a bug.

**Comment by anuveyatsu** [comment]
@starsinmypockets do you think we can close this issue?

**Comment by starsinmypockets** [comment]
WILL NOT FIX: See https://github.com/datopian/dashboard-js/issues/15
